name: codec-dev
channels:
  - conda-forge 
dependencies:
  - python>=3.13
  - pip
  - "libblas=*=*mkl" 
  - numpy 
  - matplotlib=3.*
  - numba=0.62.* # version pinned for galois 0.4.8
  - pytest
  - sphinx=7.*
  - sphinx_rtd_theme
  - biopython
  - jupyter
  - ipykernel
  - twine
  - pip:
    - galois>=0.4.8
    - build

